spring:
  profiles: test
  datasource:
    url: jdbc:mysql://${DATABASE_SERVICE_NAME:mysql}:${DB_PORT:3306}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
greeting:
  message: "Oh, you like %s!"