apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations: {}
  labels:
    app: spring-db-demo
    app.kubernetes.io/component: spring-db-demo
    app.kubernetes.io/instance: spring-db-demo
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: spring-db-demo-app
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-8-el7
  name: spring-db-demo
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: spring-db-demo:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /
    git:
      ref: main
      uri: https://github.com/cookcodeblog/spring-db-demo.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: java:openjdk-8-el7
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
