apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations: {}
  labels:
    app: spring-db-demo
    app.kubernetes.io/component: spring-db-demo
    app.kubernetes.io/instance: spring-db-demo
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: spring-db-demo-app
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-8-el7
  name: spring-db-demo
spec:
  lookupPolicy:
    local: false
